name: Docker Image CI

on:
  schedule:
    - cron: '18 15 * * *'
  push:
    branches: [ "main" , "release"]
    #paths:
    #  - "path/to/relevant/dirs/where/changes/cause/rebuilds"
    
    # TODO Automate version numbers
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-hub:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterhub

  build-and-push-lab:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterlab

  build-and-push-lab-cpu:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterlab-scipy-cpu

  build-and-push-lab-gpu:
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterlab-scipy-gpu