name: Docker Image CI

on:
  schedule:
    - cron: '18 15 * * *'
  push:
    branches: [ "develop" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      hub: ${{ steps.filter.outputs.hub }}
      lab-gpu: ${{ steps.filter.outputs.lab-gpu }}   
      lab-cpu: ${{ steps.filter.outputs.lab-cpu }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: develop

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          hub:
            - 'jupyterhub/**'
          lab-gpu:
            - 'jupyterlab-scipy-gpu/**'
          lab-cpu:
            - 'jupyterlab-scipy-cpu/**'

  build-and-push-hub:
    needs: changes
    if: ${{ needs.changes.outputs.hub == 'true' }}
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterhub
      #tag: dev

  build-and-push-lab-cpu:
    needs: changes
    if: ${{ needs.changes.outputs.lab-cpu == 'true' }}
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterlab-scipy-cpu
      #tag: dev

  build-and-push-lab-gpu:
    needs: changes
    if: ${{ needs.changes.outputs.lab-gpu == 'true' }}
    uses: ./.github/workflows/reusable-docker-build-push.yml
    with:
      image: jupyterlab-scipy-gpu
      #tag: dev