name: Generate tag

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Generate tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: PrateekKhatri/github-tag-action-1@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
