version: '3'

services:
  jupyterhubdev:
    image: ${JUPYTERHUB_IMAGE}
    #container_name: jupyterhub
    expose:
      - 8001
    ports:
      - 8985:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs_share/docker/jupyterhub:/mnt/nfs_share/docker/jupyterhub
    #      - /var/data/jupyterhub:/srv/jupyterhub
    environment:
      #- DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_JUPYTER_CONTAINERS=jupyterlab_testimg,ghcr.io/fhswf/jupyterhub/jupyterlab-scipy-gpu:main,ghcr.io/fhswf/jupyterhub/jupyterlab-scipy-cpu:main
      #- DOCKER_SPAWN_ENVS=NVIDIA_VISIBLE_DEVICES:1
      - JUPYTERHUB_SPAWNERCLASS=modules.CustomSpawner.CustomSpawner
      - DOCKER_NETWORK_NAME=jupyterhub_swarm_network_dev
      - HUB_IP=0.0.0.0 # same as serivce name or localhost
      #- HUB_CONNECT_IP=jupyterhub_jupyterhub # address accessbile from the outside
      - HOST
      - VOLUME_PATH_PREFIX=dev_userdata
      #- LAB_HUB_API_URL=jupyterhub_jupyterhub
      - JUPYTERHUB_CRYPT_KEY=${JUPYTERHUB_CRYPT_KEY}
      - HUB_BASE_URL_PREFIX=${HUB_BASE_URL_PREFIX}

      - LTI_CLIENT_KEY=${LTI_CLIENT_KEY}
      - LTI_SHARED_SECRET=${LTI_SHARED_SECRET}
      - LTI13_PRIVATE_KEY=${LTI13_PRIVATE_KEY}

      - KEYCLOAK_LOGOUT_URL=${KEYCLOAK_LOGOUT_URL}

      - OAUTH2_TLS_VERIFY=${OAUTH2_TLS_VERIFY}
      - OAUTH2_AUTHORIZE_URL=${OAUTH2_AUTHORIZE_URL}
      # because here we have communicate internally, "jupiter.fh-swf.de" gets block by fh-swf rev. proxy
      - OAUTH2_TOKEN_URL=${OAUTH2_INTERNAL_TOKEN_URL}
      #- OAUTH2_TOKEN_URL=${OAUTH2_TOKEN_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_CALLBACK_URL=${OAUTH_CALLBACK_URL}
      - OAUTH2_USERDATA_URL=${OAUTH2_INTERNAL_USERDATA_URL}
    networks:
      - traefik
      - keycloak_sso_swarm
      - jupyterhub_swarm_network_dev
      #- local_keycloak
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.${COMPOSE_PROJECT_NAME}-core.rule=PathPrefix(`${HUB_BASE_URL_PREFIX}`)
    restart: on-failure
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  keycloak_sso_swarm:
    driver: overlay
    external: true
  jupyterhub_swarm_network_dev:
    driver: overlay
    external: true
    attachable: true
  traefik:
    external: true
